### ISSUE TITLE
ドラックアンドドロップでビデオの読み込み

### ISSUE THREAD

**Issue by Licht-T** [ymnk13/UMATracker#2]

**Comment by ymnk13** [comment]
https://gist.github.com/ymnk13/e36db65490f670d85164
を参考に。
ymnk13@f07aecdc41a6db858ceaaa19a50e802fdd7b9d0d

**Comment by ymnk13** [comment]
abaffc249b787bc192c23d11c2cf79d72ad2b8e6
修正した
